// This file is generated by Firebase Studio.
'use server';

/**
 * @fileOverview Provides AI-powered task title suggestions.
 *
 * - suggestTaskTitle - A function that generates task title suggestions based on a description.
 * - SuggestTaskTitleInput - The input type for the suggestTaskTitle function.
 * - SuggestTaskTitleOutput - The return type for the suggestTaskTitle function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTaskTitleInputSchema = z.object({
  description: z.string().describe('A description of the task.'),
});
export type SuggestTaskTitleInput = z.infer<typeof SuggestTaskTitleInputSchema>;

const SuggestTaskTitleOutputSchema = z.object({
  titleSuggestion: z.string().describe('A suggested title for the task.'),
});
export type SuggestTaskTitleOutput = z.infer<typeof SuggestTaskTitleOutputSchema>;

export async function suggestTaskTitle(input: SuggestTaskTitleInput): Promise<SuggestTaskTitleOutput> {
  return suggestTaskTitleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTaskTitlePrompt',
  input: {schema: SuggestTaskTitleInputSchema},
  output: {schema: SuggestTaskTitleOutputSchema},
  prompt: `You are an AI assistant that suggests task titles based on a given description.

  Description: {{{description}}}

  Please provide a concise and descriptive title for the task.`,
});

const suggestTaskTitleFlow = ai.defineFlow(
  {
    name: 'suggestTaskTitleFlow',
    inputSchema: SuggestTaskTitleInputSchema,
    outputSchema: SuggestTaskTitleOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
